name: dev
on:
  pull_request:
    branches: [ '*' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Test core
        run: |
          cd src/core
          yarn install --frozen-lockfile --production=false
          yarn test:format
          yarn test
          yarn build
          cd ../..

      - name: Test cdk
        run: |
          cd src/cdk
          yarn install --frozen-lockfile --production=false
          yarn test:format
          yarn build
          cd ../..

      - name: Test transport
        run: |
          cd src/transport
          yarn install --frozen-lockfile --production=false
          yarn test:format
          yarn test
          yarn build
          cd ../..